In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv"
df = pd.read_csv(url)
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [4]:
df.shape

(869, 7)

In [14]:
filtered = df[(df["year"] > 1588) & (df["year"] < 1592)]
filtered.shape

(21, 7)

In [19]:
# Create column with default true
df["is_permenant"] = True

# Set false for temp embassies
temporary_places = ["Geneva", "Saxony", "Tuscany", "Ferrara"]

df.loc[df["place"].isin(temporary_places), "is_permenant"] = False

# Count the false values
df.loc[df["is_permenant"] == False].shape

(11, 8)

In [ ]:
df["place"] = df["place"].replace(["Geneva", "Grisons"], "Swiss Cantons")

869

In [31]:
(df["place"] == "Swiss Cantons").sum()

np.int64(210)

In [32]:
df_agg = df.groupby("place").agg(
    years_present=("place", "count"),
    unique_ambs=("name", "nunique")
).reset_index()

# Sort ascending by unique_ambs
df_agg = df_agg.sort_values(by="unique_ambs", ascending=True)

df_agg

                place  years_present  unique_ambs
14            Tuscany              3            1
10             Saxony              3            1
0             Denmark             40            2
2             Ferrara              3            2
9               Savoy              4            3
11           Scotland             22            4
6              Poland              7            5
7            Portugal             56            5
12              Spain             35            5
4         Netherlands             45           12
3   Holy Roman Empire             81           15
5      Ottoman Empire             89           20
15             Venice             96           20
8                Rome             82           24
1             England             93           26
13      Swiss Cantons            210           39

In [33]:
df_agg.iloc[3]["unique_ambs"]

np.int64(2)